### ISSUE TITLE
temping out past shift

### ISSUE THREAD

**Issue by toozej** [DanAlbert/whdsched#23]
low priority:  You should not be able to temp out a shift that happened in the past.  Not a big deal since a past shift that has been temped out (in the future) does not show up in the available shifts page.

**Comment by DanAlbert** [comment]
This was actually done by design. We're hoping to be able to autofill timecards with this in the long run, and people may need to temp and take shifts retroactively, as temps are often done without going through the system. Issue #13 will try to make this more apparent.
