### ISSUE TITLE
no shifts remaining for this term

### ISSUE THREAD

**Issue by toozej** [DanAlbert/whdsched#27]
message displayed when there are in fact shifts remaining for me this term. this has been known to only happen at night. This is a known issue, just documenting it here.

**Comment by DanAlbert** [comment]
Any idea what time this happened?

**Comment by toozej** [comment]
Roughly 2200 mountain last night

On Jan 6, 2012, at 12:00, Dan Albert
reply@reply.github.com
wrote:

**Comment by toozej** [comment]
same thing is happening right now, 1704 mountain standard time. I have shifts today and I just took a temp, none of them show

**Comment by toozej** [comment]
same thing as of latest push, 1/8/12 at 1601
